redis:
  hostName: 127.0.0.1
  port: 6379
  password:
  database: 0
  ttl: PT3H
  pool:
    maxIdle: 6
    minIdle: 4
    maxTotal: 32
    maxWaitMillis: 100

api:
  version: v1
  maxReqPerSec: 5
  allowedOrigin: 'http://localhost:8080'
  originFilter: /v1/get|/v1/decrypt|/v1/encrypt|/v1/store

webjars:
  bootstrap: "5.1.0"
  jquery: "3.6.0"