redis:
  isEmbeded: false
  maxMemoryMB: 128
  hostName: 127.0.0.1
  port: 6379
  password:
  database: 0
  ttlMax: PT3H
  ttlMin: PT1H
  pool:
    maxIdle: 6
    minIdle: 4
    maxTotal: 32
    maxWaitMillis: 100

api:
  r53: 3.235.20.42
  version: v1
  maxReqPerSec: 5
  filterOrigin: false
  deploy: false
  allowedOrigin: 'http://localhost:8080'

webjars:
  bootstrap: "5.1.0"
  jquery: "3.6.0"