redis:
  isEmbeded: false
  maxMemoryMB: 128
  hostName: 127.0.0.1
  port: 6379
  password:
  database: 0
  ttlMax: PT3H
  ttlMin: PT1H
  pool:
    maxIdle: 6
    minIdle: 4
    maxTotal: 32
    maxWaitMillis: 100

api:
  version: v1
  maxReqPerSec: 5
  allowedOrigin: 'http://localhost:9000'

webjars:
  bootstrap: "5.1.0"
  jquery: "3.6.0"

server:
  port: 8080

spring:
  profiles:
    active: @profileActive@

management:
  health:
    redis:
      enabled: false